name: CI (Self-Hosted)

on:
  workflow_dispatch:

jobs:
  run-local:
    runs-on: [self-hosted, windows, local] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Python Version
        run: python --version

      - name: Run Data Load locally
        run: |
          python src/data_load.py > dataload_local_log.txt 2>&1

      - name: Upload local logs
        uses: actions/upload-artifact@v4
        with:
          name: local-run-logs
          path: dataload_local_log.txt