name: CI (Self-hosted)

on:
  workflow_dispatch:

jobs:
  run-local-analysis:
    runs-on: [self-hosted, local-windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run visualization locally
        run: |
          mkdir artifacts_local
          python src/visualization.py > artifacts_local/local_run.log 2>&1
          echo "Графіки успішно згенеровано на вашому ПК!"

      - name: Upload local artifacts
        uses: actions/upload-artifact@v4
        with:
          name: local-visualization-reports
          path: artifacts_local/